In [10]:
conda install tensorflow-text==2.0


Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow-text==2.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



Note: you may need to restart the kernel to use updated packages.


In [6]:

import tensorflow_hub as hub

import pandas as pd
import numpy as np
import matplotlib as mt
import tensorflow as tf

In [2]:
encoder='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocess='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [4]:
uploaded=files.upload()

Saving antisemitism_combined.csv to antisemitism_combined.csv


In [5]:
df=pd.read_csv('/content/antisemitism_combined.csv')
df

Unnamed: 0  Unnamed: 0.1                   id  \
0              0             0  1291817243278553088   
1              1             1  1292750633104289792   
2              2             2  1275918779831238656   
3              3             3  1293090052252135424   
4              4             4  1293251961031204865   
...          ...           ...                  ...   
1216        1216          1216  1316617182244081664   
1217        1217          1217  1316363815764791296   
1218        1218          1218  1316626398853787650   
1219        1219          1219  1316630714960543750   
1220        1220          1220   772685844910080000   

                                                   text  classification  \
0                                Y'all are the future.                0   
1     Not what you think  Propagandist  PRO zionist ...               1   
2     I'm probably blackpilled due to years of zog p...               1   
3     The latest proof that trump has managed to sim...               1   
4     Your Holiness, I would like to inform you that...               1   
...                                                 ...             ...   
1216  False. No peoples or nations know Egypt more s...               0   
1217  When the harvest and the harvesters are small,...               0   
1218  According to a Hebrew Proverb the best investm...               0   
1219  There are two ways to find Hashem, three world...               0   
1220         Time to stop the Christ-killer Blairites.                1   

      type_of_antisemitism                                        image_url  \
0                      NaN  https://pbs.twimg.com/media/Ee107xJXsAIYK_l.jpg   
1                      0.0  https://pbs.twimg.com/media/EfDF2TjXYAE_a4h.jpg   
2                      0.0  https://pbs.twimg.com/media/EbT5XA8WsAYauDY.jpg   
3                      0.0  https://pbs.twimg.com/media/EfH6jEXUMAAziFs.jpg   
4                      2.0  https://pbs.twimg.com/media/EfKNNTSXkAAnCBw.jpg   
...                    ...                                              ...   
1216                   NaN  https://pbs.twimg.com/media/EkWQVebVkAIAo54.jpg   
1217                   NaN  https://pbs.twimg.com/media/EkSp6jYXcAE8sTK.jpg   
1218                   NaN  https://pbs.twimg.com/media/EkWYr4sVgAESnUz.jpg   
1219                   NaN  https://pbs.twimg.com/media/EkWcqDsXYAAqonW.jpg   
1220                   2.0  https://pbs.twimg.com/media/CrkhITeWgAAuV4R.jpg   

                                                    ocr  \
0                                                 BB hh   
1                                                   NaN   
2                                 DI\nFORTH CARO\nROHO.   
3     Verizon\nQ4%\n12:34 AM\nforward.com\nNews » Na...   
4                                                   NaN   
...                                                 ...   
1216  HOLY WAR\nCONCEPT ART\n"IF I HAVE NOT CRAVED G...   
1217                                                NaN   
1218  He is not a full man\nwho does not own a\npiec...   
1219  זה ימשך עד עולם: יט (א)\nלמנצח, יבאר כי כבוד ה...   
1220  REMAIN\nFOR\nWORKERS\nRIGHTS\nAlan Bowring\n2,...   

                                          combined_text  
0                          Y'all are the future.  BB hh  
1     Not what you think  Propagandist  PRO zionist ...  
2     I'm probably blackpilled due to years of zog p...  
3     The latest proof that trump has managed to sim...  
4     Your Holiness, I would like to inform you that...  
...                                                 ...  
1216  False. No peoples or nations know Egypt more s...  
1217  When the harvest and the harvesters are small,...  
1218  According to a Hebrew Proverb the best investm...  
1219  There are two ways to find Hashem, three world...  
1220  Time to stop the Christ-killer Blairites.  REM...  

[1221 rows x 9 columns]

In [9]:
print(df.shape)
print(df['classification'].value_counts())
text1=list(df['text'].astype(str))
text2=["hi how are you","I'm good how about you"]

(1221, 9)
0    877
1    344
Name: classification, dtype: int64


In [10]:
bert_preprocess_model=hub.KerasLayer(preprocess)

In [1]:
text_prepprocessed=bert_preprocess_model(text1)
text_prepprocessed2=bert_preprocess_model(text2)
text_prepprocessed2.keys()


NameError: ignored

In [ ]:
text_prepprocessed['input_mask']

<tf.Tensor: shape=(1221, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>

In [ ]:
text_prepprocessed['input_word_ids']

<tf.Tensor: shape=(1221, 128), dtype=int32, numpy=
array([[ 101, 1061, 1005, ...,    0,    0,    0],
       [ 101, 2025, 2054, ...,    0,    0,    0],
       [ 101, 1045, 1005, ...,    0,    0,    0],
       ...,
       [ 101, 2429, 2000, ...,    0,    0,    0],
       [ 101, 2045, 2024, ...,    0,    0,    0],
       [ 101, 2051, 2000, ...,    0,    0,    0]], dtype=int32)>

In [9]:
#text embedding 
# after the preprocessing is done(preprocesslayer) then encoder will convert into word embedding
bert_model=hub.KerasLayer(encoder)


In [10]:
#"pooled output is embedding of the complete sentence"
text_encoder=bert_model(text_prepprocessed2)
text_encoder.keys()

dict_keys(['sequence_output', 'pooled_output', 'default', 'encoder_outputs'])

In [11]:
text_encoder['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.93073255, -0.33647087, -0.6164274 , ..., -0.43614066,
        -0.68039286,  0.9347103 ],
       [-0.87767446, -0.34156016, -0.28573292, ..., -0.23643276,
        -0.67751056,  0.9264712 ]], dtype=float32)>

In [14]:
text_encoder['sequence_output']

#hi how are you 0 0 0 0<-128

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.09465063, -0.02654187, -0.12199742, ..., -0.2093084 ,
          0.17287841,  0.17406209],
        [ 0.4071438 , -0.05682156,  0.54576206, ..., -0.67560065,
          0.65504366, -0.28723058],
        [-0.21144404, -0.6873876 , -0.4670707 , ...,  0.15324087,
          0.60058475, -0.90940136],
        ...,
        [-0.11655539,  0.08226143,  0.54455817, ..., -0.03479472,
         -0.02140243,  0.14226997],
        [-0.14315769,  0.00387317,  0.6623065 , ...,  0.0428033 ,
         -0.01603688, -0.03080436],
        [-0.11335327, -0.00883858,  0.6039732 , ...,  0.08092492,
          0.0701332 , -0.09646198]],

       [[ 0.14642131, -0.06490935, -0.09334445, ..., -0.30265212,
          0.46626377,  0.15297525],
        [ 0.04335694, -0.41360468, -0.08501445, ...,  0.17349818,
          1.0036633 ,  0.910659  ],
        [ 0.60947305, -0.13742758, -0.35315916, ..., -0.00810083,
         -0.51407784, -0.33684194],
        ...,

In [15]:
text_encoder['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.16054496,  0.02398678, -0.08357001, ...,  0.02424534,
           0.06535076,  0.09464777],
         [ 0.7587162 , -0.28936446,  0.6789734 , ..., -0.5558778 ,
          -0.4075346 , -0.83912164],
         [-0.14016366,  1.4964665 , -0.9381673 , ..., -0.13163845,
           0.46850586,  0.6508265 ],
         ...,
         [-0.02025091, -0.23734611,  0.56414646, ...,  0.34027195,
          -0.41718006,  0.05051174],
         [-0.09940385, -0.2600146 ,  0.4329042 , ...,  0.3400563 ,
          -0.30339357, -0.02337778],
         [ 0.01636948, -0.1732557 ,  0.46298227, ...,  0.67358595,
          -0.6244488 , -0.0891128 ]],
 
        [[ 0.10393408,  0.06953396, -0.10970084, ...,  0.08545081,
           0.05181502,  0.05399164],
         [ 0.59146947,  1.1187493 , -0.6326692 , ...,  0.5352308 ,
           1.0089031 ,  0.06103103],
         [-0.6179014 ,  0.47927585,  0.3069623 , ...,  0.1973024 ,
           0.8415004 , -1.12