In [7]:
pip install tensorflow-text

ERROR: Could not find a version that satisfies the requirement tensorflow-text (from versions: none)
ERROR: No matching distribution found for tensorflow-text
Note: you may need to restart the kernel to use updated packages.


In [1]:

import tensorflow_hub as hub
import tensorflow_text as text
import pandas as pd
import numpy as np
import matplotlib as mt
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow_text'

In [9]:
encoder='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocess='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [2]:
import tensorflow as tf

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/dhanushkikkisetti/miniforge3/bin/python"
  * The NumPy version is: "1.23.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/dhanushkikkisetti/miniforge3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libcblas.3.dylib'
  Referenced from: '/Users/dhanushkikkisetti/miniforge3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so'
  Reason: tried: '/Users/dhanushkikkisetti/miniforge3/lib/python3.10/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/dhanushkikkisetti/miniforge3/lib/python3.10/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/dhanushkikkisetti/miniforge3/bin/../lib/libcblas.3.dylib' (no such file), '/Users/dhanushkikkisetti/miniforge3/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)


In [19]:
df=pd.read_csv('C:/Users/Dhruv Jain/Downloads/antisemitism_combined.csv')
df

Unnamed: 0.1  Unnamed: 0                   id  \
0                0           0  1291817243278553088   
1                1           1  1292750633104289792   
2                2           2  1275918779831238656   
3                3           3  1293090052252135424   
4                4           4  1293251961031204865   
...            ...         ...                  ...   
1216          1216        1216  1316617182244081664   
1217          1217        1217  1316363815764791296   
1218          1218        1218  1316626398853787650   
1219          1219        1219  1316630714960543750   
1220          1220        1220   772685844910080000   

                                                   text  classification  \
0                                Y'all are the future.                0   
1     Not what you think  Propagandist  PRO zionist ...               1   
2     I'm probably blackpilled due to years of zog p...               1   
3     The latest proof that trump has managed to sim...               1   
4     Your Holiness, I would like to inform you that...               1   
...                                                 ...             ...   
1216  False. No peoples or nations know Egypt more s...               0   
1217  When the harvest and the harvesters are small,...               0   
1218  According to a Hebrew Proverb the best investm...               0   
1219  There are two ways to find Hashem, three world...               0   
1220         Time to stop the Christ-killer Blairites.                1   

      type_of_antisemitism                                        image_url  \
0                      NaN  https://pbs.twimg.com/media/Ee107xJXsAIYK_l.jpg   
1                      0.0  https://pbs.twimg.com/media/EfDF2TjXYAE_a4h.jpg   
2                      0.0  https://pbs.twimg.com/media/EbT5XA8WsAYauDY.jpg   
3                      0.0  https://pbs.twimg.com/media/EfH6jEXUMAAziFs.jpg   
4                      2.0  https://pbs.twimg.com/media/EfKNNTSXkAAnCBw.jpg   
...                    ...                                              ...   
1216                   NaN  https://pbs.twimg.com/media/EkWQVebVkAIAo54.jpg   
1217                   NaN  https://pbs.twimg.com/media/EkSp6jYXcAE8sTK.jpg   
1218                   NaN  https://pbs.twimg.com/media/EkWYr4sVgAESnUz.jpg   
1219                   NaN  https://pbs.twimg.com/media/EkWcqDsXYAAqonW.jpg   
1220                   2.0  https://pbs.twimg.com/media/CrkhITeWgAAuV4R.jpg   

                                                    ocr  \
0                                                 BB hh   
1                                                   NaN   
2                                 DI\nFORTH CARO\nROHO.   
3     Verizon\nQ4%\n12:34 AM\nforward.com\nNews » Na...   
4                                                   NaN   
...                                                 ...   
1216  HOLY WAR\nCONCEPT ART\n"IF I HAVE NOT CRAVED G...   
1217                                                NaN   
1218  He is not a full man\nwho does not own a\npiec...   
1219  זה ימשך עד עולם: יט (א)\nלמנצח, יבאר כי כבוד ה...   
1220  REMAIN\nFOR\nWORKERS\nRIGHTS\nAlan Bowring\n2,...   

                                          combined_text  
0                          Y'all are the future.  BB hh  
1     Not what you think  Propagandist  PRO zionist ...  
2     I'm probably blackpilled due to years of zog p...  
3     The latest proof that trump has managed to sim...  
4     Your Holiness, I would like to inform you that...  
...                                                 ...  
1216  False. No peoples or nations know Egypt more s...  
1217  When the harvest and the harvesters are small,...  
1218  According to a Hebrew Proverb the best investm...  
1219  There are two ways to find Hashem, three world...  
1220  Time to stop the Christ-killer Blairites.  REM...  

[1221 rows x 9 columns]

In [21]:

text1=list(df['text'].astype(str))
text2=["hi how are you","I'm good how about you"]

In [22]:
bert_preprocess_model=hub.KerasLayer(preprocess)

In [23]:
text_prepprocessed=bert_preprocess_model(text1)
text_prepprocessed2=bert_preprocess_model(text2)
text_prepprocessed2.keys()


dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [ ]:
text_prepprocessed['input_mask']

<tf.Tensor: shape=(1221, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>

In [ ]:
text_prepprocessed['input_word_ids']

<tf.Tensor: shape=(1221, 128), dtype=int32, numpy=
array([[ 101, 1061, 1005, ...,    0,    0,    0],
       [ 101, 2025, 2054, ...,    0,    0,    0],
       [ 101, 1045, 1005, ...,    0,    0,    0],
       ...,
       [ 101, 2429, 2000, ...,    0,    0,    0],
       [ 101, 2045, 2024, ...,    0,    0,    0],
       [ 101, 2051, 2000, ...,    0,    0,    0]], dtype=int32)>

In [25]:
#text embedding 
# after the preprocessing is done(preprocesslayer) then encoder will convert into word embedding
bert_model=hub.KerasLayer(encoder)


In [26]:
#"pooled output is embedding of the complete sentence"
text_encoder=bert_model(text_prepprocessed)
text_encoder.keys()

dict_keys(['default', 'encoder_outputs', 'pooled_output', 'sequence_output'])

In [27]:
text_encoder['pooled_output']

<tf.Tensor: shape=(1221, 768), dtype=float32, numpy=
array([[-0.89336276, -0.39220968, -0.9457794 , ..., -0.85309094,
        -0.7423187 ,  0.87898225],
       [-0.8386299 , -0.44747314, -0.9116362 , ..., -0.4384187 ,
        -0.64474535,  0.7505682 ],
       [-0.75977886, -0.30469298, -0.88146985, ..., -0.7751364 ,
        -0.5776022 ,  0.8495544 ],
       ...,
       [-0.6661075 , -0.63685274, -0.9273396 , ..., -0.7382743 ,
        -0.7034709 ,  0.7853697 ],
       [-0.6925458 , -0.45816723, -0.900452  , ..., -0.8345857 ,
        -0.7157205 ,  0.5893316 ],
       [-0.9521534 , -0.5725929 , -0.9572386 , ..., -0.81296563,
        -0.6941221 ,  0.91382015]], dtype=float32)>

In [28]:
text_encoder['sequence_output']

#hi how are you 0 0 0 0<-128

<tf.Tensor: shape=(1221, 128, 768), dtype=float32, numpy=
array([[[ 1.20435685e-01,  2.29897022e-01,  2.41716392e-02, ...,
         -6.23683691e-01,  2.97713727e-01,  4.08201605e-01],
        [-5.34720421e-02, -1.53453872e-02,  8.88384342e-01, ...,
          1.93288147e-01,  6.03914917e-01, -1.31655455e-01],
        [-1.66533291e-02,  5.77774597e-03,  5.16358852e-01, ...,
          3.22478175e-01,  1.17112733e-01, -5.97718179e-01],
        ...,
        [ 2.13022858e-01,  8.84142071e-02,  7.22284019e-01, ...,
         -1.12491414e-01, -2.57281572e-01, -1.10311612e-01],
        [ 2.25567147e-01,  2.09547132e-01,  7.72582173e-01, ...,
         -2.28854567e-01, -3.11387450e-01, -1.28931090e-01],
        [ 1.15247570e-01,  2.55250692e-01,  7.52944052e-01, ...,
         -1.59431934e-01, -1.94548100e-01, -1.54933065e-01]],

       [[-2.64139622e-01, -2.67108321e-01, -2.06367597e-01, ...,
         -3.59255254e-01,  1.16049483e-01,  4.53796089e-01],
        [ 2.02606007e-01, -2.92204589e-01, -5

In [29]:
text_encoder['encoder_outputs']

[<tf.Tensor: shape=(1221, 128, 768), dtype=float32, numpy=
 array([[[ 2.55702958e-02,  8.86001140e-02, -2.12937981e-01, ...,
           2.04766721e-01, -3.63131911e-02, -2.25014091e-02],
         [ 1.16287208e+00,  5.44603586e-01,  3.55088234e-01, ...,
           4.51383054e-01,  2.05909634e+00,  1.65701532e+00],
         [-4.77466762e-01,  3.93286020e-01,  3.13964128e-01, ...,
          -2.86189735e-01,  1.05625331e+00, -1.44358742e+00],
         ...,
         [-8.69527832e-02, -1.78870499e-01,  5.76440454e-01, ...,
           3.16708654e-01, -3.46454710e-01, -5.01808152e-02],
         [-1.68010026e-01, -1.87006265e-01,  4.59707022e-01, ...,
           3.13919544e-01, -2.48228163e-01, -1.26817420e-01],
         [-7.00834394e-02, -1.18177801e-01,  4.78090763e-01, ...,
           6.12090766e-01, -5.20262957e-01, -1.75874904e-01]],
 
        [[ 1.00146383e-01,  7.68821985e-02, -1.47528946e-01, ...,
           1.38368905e-01, -1.80038176e-02, -2.72328034e-03],
         [ 1.45852402e-01,  