In [1]:
pip uninstall tensorflow --yes


Found existing installation: tensorflow 2.10.0
Uninstalling tensorflow-2.10.0:
  Successfully uninstalled tensorflow-2.10.0
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install tensorflow 

  Using cached tensorflow-2.10.0-cp39-cp39-macosx_10_14_x86_64.whl (241.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install tensorflow_hub

  Using cached tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.2/484.2 kB 8.8 MB/s eta 0:00:0000:01
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import pandas as pd
import numpy as np
import matplotlib as mt
import tensorflow as tf



In [1]:
encoder='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocess='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [ ]:
uploaded=files.upload()

Saving antisemitism_combined.csv to antisemitism_combined.csv


In [ ]:
df=pd.read_csv('/content/antisemitism_combined.csv')
df

Unnamed: 0  Unnamed: 0.1                   id  \
0              0             0  1291817243278553088   
1              1             1  1292750633104289792   
2              2             2  1275918779831238656   
3              3             3  1293090052252135424   
4              4             4  1293251961031204865   
...          ...           ...                  ...   
1216        1216          1216  1316617182244081664   
1217        1217          1217  1316363815764791296   
1218        1218          1218  1316626398853787650   
1219        1219          1219  1316630714960543750   
1220        1220          1220   772685844910080000   

                                                   text  classification  \
0                                Y'all are the future.                0   
1     Not what you think  Propagandist  PRO zionist ...               1   
2     I'm probably blackpilled due to years of zog p...               1   
3     The latest proof that trump has managed to sim...               1   
4     Your Holiness, I would like to inform you that...               1   
...                                                 ...             ...   
1216  False. No peoples or nations know Egypt more s...               0   
1217  When the harvest and the harvesters are small,...               0   
1218  According to a Hebrew Proverb the best investm...               0   
1219  There are two ways to find Hashem, three world...               0   
1220         Time to stop the Christ-killer Blairites.                1   

      type_of_antisemitism                                        image_url  \
0                      NaN  https://pbs.twimg.com/media/Ee107xJXsAIYK_l.jpg   
1                      0.0  https://pbs.twimg.com/media/EfDF2TjXYAE_a4h.jpg   
2                      0.0  https://pbs.twimg.com/media/EbT5XA8WsAYauDY.jpg   
3                      0.0  https://pbs.twimg.com/media/EfH6jEXUMAAziFs.jpg   
4                      2.0  https://pbs.twimg.com/media/EfKNNTSXkAAnCBw.jpg   
...                    ...                                              ...   
1216                   NaN  https://pbs.twimg.com/media/EkWQVebVkAIAo54.jpg   
1217                   NaN  https://pbs.twimg.com/media/EkSp6jYXcAE8sTK.jpg   
1218                   NaN  https://pbs.twimg.com/media/EkWYr4sVgAESnUz.jpg   
1219                   NaN  https://pbs.twimg.com/media/EkWcqDsXYAAqonW.jpg   
1220                   2.0  https://pbs.twimg.com/media/CrkhITeWgAAuV4R.jpg   

                                                    ocr  \
0                                                 BB hh   
1                                                   NaN   
2                                 DI\nFORTH CARO\nROHO.   
3     Verizon\nQ4%\n12:34 AM\nforward.com\nNews » Na...   
4                                                   NaN   
...                                                 ...   
1216  HOLY WAR\nCONCEPT ART\n"IF I HAVE NOT CRAVED G...   
1217                                                NaN   
1218  He is not a full man\nwho does not own a\npiec...   
1219  זה ימשך עד עולם: יט (א)\nלמנצח, יבאר כי כבוד ה...   
1220  REMAIN\nFOR\nWORKERS\nRIGHTS\nAlan Bowring\n2,...   

                                          combined_text  
0                          Y'all are the future.  BB hh  
1     Not what you think  Propagandist  PRO zionist ...  
2     I'm probably blackpilled due to years of zog p...  
3     The latest proof that trump has managed to sim...  
4     Your Holiness, I would like to inform you that...  
...                                                 ...  
1216  False. No peoples or nations know Egypt more s...  
1217  When the harvest and the harvesters are small,...  
1218  According to a Hebrew Proverb the best investm...  
1219  There are two ways to find Hashem, three world...  
1220  Time to stop the Christ-killer Blairites.  REM...  

[1221 rows x 9 columns]

In [ ]:
text1=list(df['text'].astype(str))
text2=["hi how are you","im good how about you"]

In [2]:
bert_preprocess_model=hub.KerasLayer(preprocess)

NameError: name 'hub' is not defined

In [ ]:
text_prepprocessed=bert_preprocess_model(text1)
text_prepprocessed.keys()


dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [ ]:
text_prepprocessed['input_mask']

<tf.Tensor: shape=(1221, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>

In [ ]:
text_prepprocessed['input_word_ids']

<tf.Tensor: shape=(1221, 128), dtype=int32, numpy=
array([[ 101, 1061, 1005, ...,    0,    0,    0],
       [ 101, 2025, 2054, ...,    0,    0,    0],
       [ 101, 1045, 1005, ...,    0,    0,    0],
       ...,
       [ 101, 2429, 2000, ...,    0,    0,    0],
       [ 101, 2045, 2024, ...,    0,    0,    0],
       [ 101, 2051, 2000, ...,    0,    0,    0]], dtype=int32)>

In [ ]:
#text embedding 
# after the preprocessing is done(preprocesslayer) then encoder will convert into word embedding
bert_model=hub.KerasLayer(encoder)


In [ ]:
#"pooled output is embedding of the complete sentence"
text_encoder=bert_model(text_prepprocessed)
text_encoder.keys()